FROM maven:3.9.6-amazoncorretto-17 AS build

WORKDIR /project

COPY pom.xml .
RUN mvn dependency:go-offline

COPY src/ /project/src

RUN mvn package

FROM eclipse-temurin:17-jdk

RUN mkdir /app

RUN addgroup -g 1001 -S tecogroup

RUN adduser -S teco -u 1001

COPY --from=build /project/target/gokartservice-0.0.1-SNAPSHOT.jar /app/gokart-service.jar

WORKDIR /app

RUN chown -R teco:tecogroup /app

EXPOSE 8000

CMD java $JAVA_OPTS -jar gokart-service.jar